# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Imager-Simple
version:      0.01
version_from: lib/Imager/Simple.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Accessor::Fast:         0
    Imager:                        0
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
